// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjayeVlms0WmtDc-3xaJ63NVftI6TaF1M',
    appId: '1:313522714158:web:58dd84d2fd3a51a1d551bf',
    messagingSenderId: '313522714158',
    projectId: 'cinescope-firebase',
    authDomain: 'cinescope-firebase.firebaseapp.com',
    storageBucket: 'cinescope-firebase.firebasestorage.app',
    measurementId: 'G-N28Q0VVBV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9Z0Z0-KkUOG7e5qnF3nkXsb0nUe7P8Vs',
    appId: '1:313522714158:android:78412f1cac52d1efd551bf',
    messagingSenderId: '313522714158',
    projectId: 'cinescope-firebase',
    storageBucket: 'cinescope-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_PUFkdgxmenqb0i4XVboWMhB_-ReFuX4',
    appId: '1:313522714158:ios:5900e80db2c41e40d551bf',
    messagingSenderId: '313522714158',
    projectId: 'cinescope-firebase',
    storageBucket: 'cinescope-firebase.firebasestorage.app',
    iosBundleId: 'com.example.projectMovie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_PUFkdgxmenqb0i4XVboWMhB_-ReFuX4',
    appId: '1:313522714158:ios:5900e80db2c41e40d551bf',
    messagingSenderId: '313522714158',
    projectId: 'cinescope-firebase',
    storageBucket: 'cinescope-firebase.firebasestorage.app',
    iosBundleId: 'com.example.projectMovie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjayeVlms0WmtDc-3xaJ63NVftI6TaF1M',
    appId: '1:313522714158:web:6951e2f4f7f71859d551bf',
    messagingSenderId: '313522714158',
    projectId: 'cinescope-firebase',
    authDomain: 'cinescope-firebase.firebaseapp.com',
    storageBucket: 'cinescope-firebase.firebasestorage.app',
    measurementId: 'G-SW03GE38QN',
  );
}
